package cl.komatsu.ingresoordenservicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-07-12T08:59:04.100-04:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://ingresoordenservicio.komatsu.cl", name = "IngresoOrdenServicioPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IngresoOrdenServicioPortType {

    @WebMethod(operationName = "IngresoOrdenServicio", action = "urn:IngresoOrdenServicio")
    @Action(input = "urn:IngresoOrdenServicio", output = "urn:IngresoOrdenServicioResponse")
    @RequestWrapper(localName = "IngresoOrdenServicio", targetNamespace = "http://ingresoordenservicio.komatsu.cl", className = "cl.komatsu.ingresoordenservicio.IngresoOrdenServicio")
    @ResponseWrapper(localName = "IngresoOrdenServicioResponse", targetNamespace = "http://ingresoordenservicio.komatsu.cl", className = "cl.komatsu.ingresoordenservicio.IngresoOrdenServicioResponse")
    public void ingresoOrdenServicio(

        @WebParam(name = "AUFNR", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String aufnr,
        @WebParam(name = "FKDAT", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String fkdat,
        @WebParam(name = "MAUFNR", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String maufnr,
        @WebParam(name = "AUART", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String auart,
        @WebParam(name = "KDAUF", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String kdauf,
        @WebParam(name = "ERDAT", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String erdat,
        @WebParam(name = "KTEXT", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String ktext,
        @WebParam(name = "SYSST", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String sysst,
        @WebParam(name = "BUKRS", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String bukrs,
        @WebParam(name = "VAPLZ", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String vaplz,
        @WebParam(name = "PLGRP", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String plgrp,
        @WebParam(name = "KUNUM", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String kunum,
        @WebParam(name = "NAME1", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String name1,
        @WebParam(name = "EQUNR", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String equnr,
        @WebParam(name = "SHTXT", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String shtxt,
        @WebParam(name = "EQART", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String eqart,
        @WebParam(name = "SERNR", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String sernr,
        @WebParam(name = "MATNR", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String matnr,
        @WebParam(name = "RECDV", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String recdv,
        @WebParam(name = "ILART", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String ilart,
        @WebParam(name = "TYPBZ", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String typbz,
        @WebParam(name = "SWERK", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String swerk,
        @WebParam(name = "STORT", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String stort,
        @WebParam(name = "KOSTV", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String kostv,
        @WebParam(name = "PRCTR", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        java.lang.String prctr,
        @WebParam(name = "OPERACIONES", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        cl.komatsu.ingresoordenservicio.ListaoperacionesType operaciones,
        @WebParam(mode = WebParam.Mode.OUT, name = "RESPONSE", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        javax.xml.ws.Holder<java.lang.String> response,
        @WebParam(mode = WebParam.Mode.OUT, name = "DETAIL", targetNamespace = "http://ingresoordenservicio.komatsu.cl")
        javax.xml.ws.Holder<java.lang.String> detail
    );
}
