package cl.komatsu.ingresoordenservicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-07-12T08:59:04.165-04:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "IngresoOrdenServicio",
                  wsdlLocation = "file:/C:/komatsu-proyectos/FUSE-Migraciones/KCC-FUSE-Ordenes-Servicio-Extraccion-Cola/src/main/resources/static/wsdl/ingreso_orden_servicio.wsdl",
                  targetNamespace = "http://ingresoordenservicio.komatsu.cl")
public class IngresoOrdenServicio_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ingresoordenservicio.komatsu.cl", "IngresoOrdenServicio");
    public final static QName IngresoOrdenServicioSoapEndpoint = new QName("http://ingresoordenservicio.komatsu.cl", "IngresoOrdenServicioSoapEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/komatsu-proyectos/FUSE-Migraciones/KCC-FUSE-Ordenes-Servicio-Extraccion-Cola/src/main/resources/static/wsdl/ingreso_orden_servicio.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IngresoOrdenServicio_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/komatsu-proyectos/FUSE-Migraciones/KCC-FUSE-Ordenes-Servicio-Extraccion-Cola/src/main/resources/static/wsdl/ingreso_orden_servicio.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IngresoOrdenServicio_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IngresoOrdenServicio_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IngresoOrdenServicio_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IngresoOrdenServicio_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IngresoOrdenServicio_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IngresoOrdenServicio_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IngresoOrdenServicioPortType
     */
    @WebEndpoint(name = "IngresoOrdenServicioSoapEndpoint")
    public IngresoOrdenServicioPortType getIngresoOrdenServicioSoapEndpoint() {
        return super.getPort(IngresoOrdenServicioSoapEndpoint, IngresoOrdenServicioPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IngresoOrdenServicioPortType
     */
    @WebEndpoint(name = "IngresoOrdenServicioSoapEndpoint")
    public IngresoOrdenServicioPortType getIngresoOrdenServicioSoapEndpoint(WebServiceFeature... features) {
        return super.getPort(IngresoOrdenServicioSoapEndpoint, IngresoOrdenServicioPortType.class, features);
    }

}
